# -*- coding: utf-8 -*-
"""Haciendo_cuentas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzTmzuE41OBYx5cOt8sKnfXu8tWtHKKp

1. Hacer un formulario en donde se ingrese el saldo inicial, el interes mensual, el valor del seguro y el número de cuotas y nos arroje un listado de pago por cada cuota.

### Resolver el problema a mano o planteamiento inicial
"""

#Solicitar variables inciales
saldo_inicial = 10000000
numero_cuotas = 12
int_mensual = 0.01
seguro = 2000

#Calcular valores importantes
abono_capital = saldo_inicial/numero_cuotas
abono_capital

#La variable por cada iteración
saldo = saldo_inicial
pago_intereses = saldo*int_mensual
pago_intereses

valor_a_pagar = abono_capital + pago_intereses + seguro

saldo = saldo - abono_capital
saldo

#Comenzamos una segunda iteración
pago_intereses = saldo*int_mensual
pago_intereses

valor_a_pagar = abono_capital + pago_intereses + seguro
valor_a_pagar

"""### Plantamiento en código"""

saldo_inicial = 10000000
numero_cuotas = 12
int_mensual = 0.01
seguro = 2000
# round (valor, cuantas cifras) 3 --> redondeo a 3 cifras
abono_capital = round(saldo_inicial/numero_cuotas, 3)
saldo = saldo_inicial
pago_intereses = saldo*int_mensual
for i in range(1,numero_cuotas+1):
  pago_intereses = round(saldo*int_mensual, 3)
  valor_a_pagar = round(abono_capital + pago_intereses + seguro, 3)
  print(f"En la cuota #{i} el valor a pagar es {valor_a_pagar}")
  saldo = round(saldo - abono_capital, 3)

"""### Presentación"""

#@title Calculadora de cuotas
saldo_inicial =  5000000#@param {type:"number"}
numero_cuotas =  36#@param {type:"integer"}
seguro =  2000#@param {type:"number"}
int_mensual =  0.015#@param {type:"number"}

abono_capital = round(saldo_inicial/numero_cuotas, 3)
saldo = saldo_inicial
pago_intereses = saldo*int_mensual
for i in range(1,numero_cuotas+1):
  pago_intereses = round(saldo*int_mensual, 3)
  valor_a_pagar = round(abono_capital + pago_intereses + seguro, 3)
  print(f"En la cuota #{i} el valor a pagar es {valor_a_pagar}")
  saldo = round(saldo - abono_capital, 3)

"""## Segundo punto

2. Una empresa quiere implementar un servicio de credito rápido para sus trabajadores con un descuento por nomina. Este crédito será de couta variable y ésta podrá ser de un máximo de 30% de ingreso libre. Dicha empresa está formada por

| Tipo  | Ingreso Libre | Porcentaje_en_la_empresa  |
|---|---|---|
| A | 800.000  | 70%  |
| B, C, D | 2'000.000 +/- 700.000   | 30%  |


El objetivo de este crédito es ser un beneficio, en el cual se incentiva el ser pagado lo más pronto posible, por lo tanto su interes mensual depende del tiempo de toma:

| Tiempo  | Interes |
|---|---|
| 3 meses | 1%  |
| 6 meses | 1.2%  |
| 12 meses | 1.5%  |

Cree un diccionario en python que indique cual sería el valor máximo de cuota y el valor máximo de monto a prestar para cada tiempo (3, 6, 12 meses) según dicha couta.
"""

informacion = {'Tipo_A':{'salario_base':800000},
               'Tipo_B':{'salario_base':1300000},
               'Tipo_C':{'salario_base':2000000},
               'Tipo_D':{'salario_base':2700000},
}

salario_base = 800000
cuota_max = salario_base*0.3
cuota_max

#Primera cuota (seguro=0)
#abono_capital = saldo_inicial/numero_cuotas
#pago_intereses = saldo_inicial*int_mensual
#valor_a_pagar = abono_capital + pago_intereses

#Reescribir valor_a_pagar
#valor_a_pagar = saldo_inicial/numero_cuotas + saldo_inicial*int_mensual
#valor_a_pagar = saldo_inicial(1/numero_cuotas + int_mensual)
#saldo_inicial = valor_a_pagar/(1/numero_cuotas + int_mensual)

numero_cuotas = 12
int_mensual = 0.015
valor_a_pagar = cuota_max

saldo_inicial = valor_a_pagar/(1/numero_cuotas + int_mensual)
saldo_inicial

numero_cuotas = 3
int_mensual = 0.01
valor_a_pagar = cuota_max

saldo_inicial = valor_a_pagar/(1/numero_cuotas + int_mensual)
saldo_inicial

numero_cuotas = 6 #3,6,12
int_mensual = 0.02#Depende del numero de cuotas (diccionario)
salario_base = 700000 #4 salarios

cuota_max = salario_base*0.3
valor_a_pagar = cuota_max
saldo_inicial = valor_a_pagar/(1/numero_cuotas + int_mensual)
print("El monto máximo a prestar es de",saldo_inicial, "para",numero_cuotas,"meses")

